add_content에서는 vetorizing의 전 과정으로 report_contentfmf column에 추가시키는 작업을 수행

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from konlpy.tag import Kkma
from konlpy.tag import Komoran
from konlpy.tag import Hannanum
from konlpy.tag import Okt

In [5]:
from eunjeon import Mecab

In [4]:
import time

In [22]:
import warnings
warnings.filterwarnings(action='ignore')

In [7]:
okt = Okt()
mecab = Mecab()

In [23]:
df = pd.read_csv('sampled_df.csv',index_col = 0)
df

,작성일,code,제목,목표주가,투자의견,작성자,제공출처,idx
50639,2018-04-18,88350,한화생명(088350)1조원 신종자본증권 발행 성공,11000,buy,박혜진,이베스트증권,473108
87611,2016-05-23,92070,디엔에프(092070),17000,buy,박유악,메리츠종금증권,380646
113571,2014-07-29,270,기아차(000270),77000,buy,이윤석,SK증권,329427
32806,2019-04-03,35720,카카오(035720)카카오페이 핵심 이슈 점검!!,135000,buy,성종화,이베스트증권,519412
81924,2016-09-12,20560,아시아나항공(020560),5300,buy,정유석,교보증권,391416
...,...,...,...,...,...,...,...,...
151362,2011-11-14,830,삼성물산 (000830),110000,strongbuy,"김열매,박판근",현대증권,272705
151440,2011-11-11,97230,한진중공업(097230),40000,strongbuy,서정덕,메리츠증권,272587
151453,2011-11-10,210,대림산업 (000210),166000,strongbuy,"이왕상,이창희",우리증권,272570
151630,2011-11-07,10620,현대미포조선 (010620),143000,strongbuy,정동익,한화증권,272294
151698,2011-11-04,33630,SK브로드밴드 (033630),5000,strongbuy,박종수,한화증권,272201

In [24]:
df1= df[['작성일','code','투자의견','idx']]

In [25]:
df1.index = df1.idx
df1['report'] = np.nan

In [26]:
df1

               작성일   code       투자의견     idx  report
idx
473108  2018-04-18  88350        buy  473108     NaN
380646  2016-05-23  92070        buy  380646     NaN
329427  2014-07-29    270        buy  329427     NaN
519412  2019-04-03  35720        buy  519412     NaN
391416  2016-09-12  20560        buy  391416     NaN
...            ...    ...        ...     ...     ...
272705  2011-11-14    830  strongbuy  272705     NaN
272587  2011-11-11  97230  strongbuy  272587     NaN
272570  2011-11-10    210  strongbuy  272570     NaN
272294  2011-11-07  10620  strongbuy  272294     NaN
272201  2011-11-04  33630  strongbuy  272201     NaN

[21261 rows x 5 columns]

In [29]:
import os
import re

txt_path = './report_text/txt/'
path = os.listdir(txt_path)
Series_txt_path = pd.Series(path)

def han_text_clean(text):
    text = re.sub("[^가-힣ㄱ-ㅎa-zA-Z ]", "", text)
   
    return text


def idx_to_open_txt(path, idx):
    txt_file = Series_txt_path[Series_txt_path.str.contains(idx)].values[0]
    with open(path+txt_file, 'r', encoding='utf-8') as f:
        read=f.readlines()
    return read


idx_list = df1.idx.values.tolist()

for n,i in enumerate(idx_list) :
    report_temp = idx_to_open_txt(txt_path,str(i))
    clean_report = han_text_clean(report_temp[0])
    df1.loc[i,'report'] = clean_report

In [35]:
df1.to_csv('add_content.csv')

In [2]:
pd.read_csv('add_content.csv')

,idx,작성일,code,투자의견,idx.1,report
0,473108,2018-04-18,88350,buy,473108,년 월 일 기업분석건설유틸리티 한화생명 기업이슈 브리프보험 년 월 일 ...
1,380646,2016-05-23,92070,buy,380646,Microsoft PowerPoint 반도체산업전망 veditingFFpptxCo...
2,329427,2014-07-29,270,buy,329427,Microsoft Word CUNITdoc기아차 Q Review 하반기 해볼만하...
3,519412,2019-04-03,35720,buy,519412,년 월 일 기업분석건설유틸리티 카카오 기업이슈 브리프인터넷게임 년 월 ...
4,391416,2016-09-12,20560,buy,391416,Microsoft Word 아시아나항공 Research Center ...
...,...,...,...,...,...,...
21256,272705,2011-11-14,830,strongbuy,272705,Microsoft Word Type산업건설엔지니어링doc 중...
21257,272587,2011-11-11,97230,strongbuy,272587,DFFFDCDCFCDFBFBEFFBEBEFBAEABAECCFFBCADCABFFBEB...
21258,272570,2011-11-10,210,strongbuy,272570,Microsoft Word IBSPPRdoc wwwwooriwmcom 분기 실...
21259,272294,2011-11-07,10620,strongbuy,272294,Microsoft Word 현대미포조선doc 현대미포조선 Big...
21260,272201,2011-11-04,33630,strongbuy,272201,Microsoft Word SK브로드밴드doc SK브로드밴드 ...